/*
 * $Workfile: driver_version.h $
 * $Revision: 1.1.2.1 $
 * $Archive: /AEP1000/Host/Drivers/Linux/2.4/driver_version.h $
 * $Date: 2001/11/14 13:08:14 $
 *
 * $CN{$
 *
 * Copyright (c) 1999-2001 Accelerated Encryption Processing Ltd. (AEP)
 * 39/40 Upper Mount Street, Dublin 2, Ireland.
 * All Rights Reserved.
 *
 * THIS SOFTWARE OR DOCUMENTATION IS THE CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF AEP ("CONFIDENTIAL INFORMATION") YOU SHALL NOT DISCLOSE
 * SUCH CONFIDENTIAL INFORMATION AND SHALL USE IT ONLY IN ACCORDANCE WITH THE
 * TERMS OF WRITTEN LICENCE AGREEMENTS AND/OR NON-DISCLOSURE AGREEMENTS
 * ENTERED INTO WITH AEP.
 * AEP PROVIDES NO WARRANTY AS TO THE QUALITY OF THIS SOFTWARE OR
 * DOCUMENTATION OR ITS SUITABILITY FOR ANY PARTICULAR PURPOSE AND TO THE
 * EXTENT PERMITTED BY LAW YOU HEREBY WAIVE ANY RIGHTS TO COMPENSATION FOR
 * DAMAGES WHETHER DIRECT OR CONSEQUENTIAL CAUSED BY THIS SOFTWARE. NO PART
 * OF THIS SOFTWARE OR DOCUMENTATION MAY BE REPRODUCED; TRANSMITTED;
 * TRANSCRIBED; STORED IN A RETRIEVAL SYSTEM; OR TRANSLATED INTO ANY
 * LANGUAGE OR COMPUTER  LANGUAGE IN ANY FORM OR BY ANY MEANS ELECTRONIC;
 * MECHANICAL; MAGNETIC; OPTICAL; CHEMICAL; MANUAL OR OTHERWISE, EXCEPT IN
 * ACCORDANCE WITH LICENSE AGREEMENTS YOU HAVE ENTERED INTO, WITHOUT THE
 * PRIOR WRITTEN PERMISSION OF AEP.
 *
 * $}CN$
 */

/* The version of the driver - should be passed in by the "make" if necessary */
#ifndef DRIVER_VERSION
#define DRIVER_VERSION "UNLABELLED"
#endif

static char aep_version_str[100] = "AEP Device Driver. Version: ";

