#
# Makefile for the Linux EDP2 layer.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definition is now in the main makefile...

export-objs = edp2.o

obj-$(CONFIG_EDP2) := edp2.o

include $(TOPDIR)/Rules.make

