#   -*-Makefile-*- template for the magarac kernel module and driver.
#
#   Copyright 1996 Olaf Titz <olaf@bigred.inka.de>
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version
#   2 of the License, or (at your option) any later version.

O_TARGET := megar.o

obj-y := 
obj-m := 

obj-$(CONFIG_CRYPTO_AEP) += megarac.o

include $(TOPDIR)/Rules.make

