# $Header: /afs/rchland.ibm.com/usr8/ibmsis/devel/ipr/ipr/src/version.mk,v 1.2.2.3 2003/11/10 19:19:51 bjking1 Exp $

IPR_MAJOR_RELEASE=1
IPR_MINOR_RELEASE=0
IPR_FIX_LEVEL=4
IPR_FIX_DATE=(April 15, 2004)

IPR_VERSION_STR=Ver. $(IPR_MAJOR_RELEASE) Rev. $(IPR_MINOR_RELEASE).$(IPR_FIX_LEVEL)

IPR_DEFINES = -DIPR_MAJOR_RELEASE=$(IPR_MAJOR_RELEASE) \
		 -DIPR_MINOR_RELEASE=$(IPR_MINOR_RELEASE) \
		 -DIPR_FIX_LEVEL=$(IPR_FIX_LEVEL) \
		 -DIPR_FIX_DATE='"$(IPR_FIX_DATE)"' \
		 -DIPR_VERSION_STR='"$(IPR_VERSION_STR)"'
